### ISSUE TITLE
封装的很棒！请问后续是否考虑封装 Proto DataStore？

### ISSUE THREAD

**Issue by Xeldow** [DylanCaiCoding/DataStoreKTX#1]

**Comment by DylanCaiCoding** [comment]
不好封装，因为很多用法是靠编译后生成的类，并不可控，做过一些尝试感觉没比官方用法好多少

**Comment by Xeldow** [comment]
好的~感谢回复！&nbsp;


肖大
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月2日(星期五) 下午4:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DylanCaiCoding/DataStoreKTX] 封装的很棒！请问后续是否考虑封装 Proto DataStore？ (Issue #1)





 
不好封装，因为很多用法是靠编译后生成的类，并不可控，做过一些尝试感觉没比官方用法好多少
